


build:
	make -C src/ build
clean:
	make -C src/ clean
rebuild:
	make -C src/ rebuild
load:
	make -C src/ load
unload:
	make -C src/ unload
reload:
	make -C src/ reload
backup:
	tar -cvjf ../megavm_hga.tar.bz2 *

